### ISSUE TITLE
Search Functionality

### ISSUE THREAD

**Issue by TrustfulDev** [DevHomies/LikeHome#11]
Requirement(s): Needs the database for hotels to be completed
- Frontend team should work on a search bar and update the page when searching
- Backend teams work with frontend team to ensure that the database is reachable (fetching, etc)

**Comment by TrustfulDev** [comment]
Home page with the search component is finished. We need to find a way to send the data to the search page. Might have to use the react hook useContext and wrap the entire application in it.

**Comment by rhedgeco** [comment]
Closing with @reddesignsguy PR merge. Open a new issue if there are problems with search. We should try to have smaller scale isses. Let me know if we need another one right away @TrustfulDev
