### ISSUE TITLE
Database for Hotel

### ISSUE THREAD

**Issue by lianh9** [DevHomies/LikeHome#21]
Hotel database model, not yet registered in the admin.py or migrated: 
1. Maybe need to add hotel amenities(separate database model or under hotel database model)
2. Depending on our implementation, might need to add image attribute for hotel model 

![1](https://user-images.githubusercontent.com/90004911/225748653-81a1295a-9d61-4725-87eb-eb2c2a5c0120.jpg)
![2](https://user-images.githubusercontent.com/90004911/225748674-54b28935-48bb-4d1e-a39c-79f4f7c24a8d.jpg)

**Comment by TrustfulDev** [comment]
Finished! Queries work and all attributes are accounted for.
