### ISSUE TITLE
Development Environment and how to run instructions

### ISSUE THREAD

**Issue by rhedgeco** [DevHomies/LikeHome#6]
We should have instructions on how to set up the dev environment and run the software in the readme for later reference.

**Comment by TrustfulDev** [comment]
Yea that sounds like a good idea, we'll do it after we set up the environments.

**Comment by TrustfulDev** [comment]
I added run instructions for the Client dev environment, but I have no idea how to run the server for Django. If possible, review what I wrote and add the instructions for the server dev environment. Thanks

**Comment by rhedgeco** [comment]
Closing as it was resolved by #19
