### ISSUE TITLE
Figma Designs

### ISSUE THREAD

**Issue by TrustfulDev** [DevHomies/LikeHome#8]
Upload your finalized Figma designs here. Make sure to label what page/component the design is for!

**Comment by maikeruzu** [comment]
### My initial figma design for the login/signup page and home page

[https://www.figma.com/file/RYUbye8IP6YF808lE1CbwX/Untitled?node-id=0%3A1&t=X4vuQvLarvLmZAQY-1](url)

**Comment by MichaelMagbual** [comment]
### Initial Figma mockup designs for LikeHome home page, user login and user registration. 
![CMPE165 LikeHome UI mockup](https://user-images.githubusercontent.com/54655520/223611272-e40502b7-40fe-4a7d-a8c1-789509bdc37c.jpg)

**Comment by Surafelgit** [comment]
My Figma Login, Registration, and Reservation page respectively. 
<img width="1440" alt="signIn" src="https://user-images.githubusercontent.com/98507332/223613367-f7c0ade2-ec4a-49e2-94a3-e8842a669653.png">
<img width="1440" alt="registr" src="https://user-images.githubusercontent.com/98507332/223613406-5ac73a5c-8bf0-48ef-a12f-2e16428f2ed9.png">
<img width="1440" alt="page" src="https://user-images.githubusercontent.com/98507332/223613427-eaa36195-7b77-447f-a302-0de9b623276b.png">

**Comment by reddesignsguy** [comment]
**#1 Sign Up/Login**
<img width="624" alt="image" src="https://user-images.githubusercontent.com/49921782/224468035-f60a8859-8694-479d-a9fe-328329788291.png">

<img width="581" alt="image" src="https://user-images.githubusercontent.com/49921782/224468115-ae90e36d-7109-49ae-86fc-09a1036fb3f7.png">

**#2 Landing Page (No need for Hotels options on navbar) **
<img width="433" alt="image" src="https://user-images.githubusercontent.com/49921782/224468400-d20fa989-36ca-4748-92d4-ece4b862b959.png">

**#3 Search**
<img width="359" alt="image" src="https://user-images.githubusercontent.com/49921782/224468548-aa1c8160-220a-409d-ac80-431e4f207f5e.png">

**#4 Hotel Details**
<img width="323" alt="image" src="https://user-images.githubusercontent.com/49921782/224468557-fa894996-c871-4dbb-87b9-ac080dfdb6a2.png">

Almost ready: Pages for... Account, Reservations, Reward Pts, Payment

**Comment by reddesignsguy** [comment]
#5 Account Page
<img width="698" alt="image" src="https://user-images.githubusercontent.com/49921782/224519364-9a858156-45ce-4c08-b764-d44a54d73645.png">

**Comment by reddesignsguy** [comment]
#6 Drop-down Account (Top right symbol)
<img width="251" alt="image" src="https://user-images.githubusercontent.com/49921782/224519384-00b2ee60-3e1f-4fbc-ad0c-53b947e406fc.png">
