### ISSUE TITLE
Database for Authentication

### ISSUE THREAD

**Issue by TrustfulDev** [DevHomies/LikeHome#9]
We're going to at least need a database for authentication by the 3/21 Demo

**Comment by xiyuanzhou** [comment]
http://127.0.0.1:8000/admin/
when run the server opens this link will guide to the Django administration, which can see/modify all the user data or models 

For the admin staff account(superuser), log in to the administration:
email: managers@example.com
username: managers
password: backend123

**Comment by xiyuanzhou** [comment]
To show new models in Django administration, need to modify admin.py to register new models.
<img width="784" alt="Screen Shot 2023-03-12 at 6 45 38 PM" src="https://user-images.githubusercontent.com/99446193/224589784-a886a36f-bc86-49ec-93a9-a7a6f2cabb24.png">
